apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ledger-api-ingress
  namespace: ledger
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: ledger-api.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ledger-api
                port:
                  number: 80
