---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ledger-api-secrets
  namespace: ledger
spec:
  encryptedData:
    DB_PASSWORD: AgCLhzSo57pHwLy/Qt4bADRkYoSHFEt3ntfEik5PT3CJsOcNXddPDSzd57wC7XPiKzFx4L8wXexupwUbQO0bzR4CxtPoRipVSxfUvnLkY3Erw33XG445JDheXpoj9aXuvCNijGC8qmiKUIZqOt5DvrhQTsFWtmtXqBJTtQUOpPhAzqQLIDPXLFrgZTrWqLq2+nQdDdblIwAqN35atxmtV+OnM6MV+jSeBDOKMlVknatPgA2R0CbQVevSjgL/1AiyDwrZuX8VIQ8u/eoxsyWsjL3MeGZKNZgFDQxpnYGctw/uE7YQkfYjzsQNR0JlxDWhWquql/p581YspDUfCsxGbFLmUu4E71GAnlnfhUF75MJ7Y4uday1m1dNBDYP3jVXTx02dQ6BIErOjmJrDSflgLmj+SZ086enKUftXh2eUubJfRK2BRDbse9Siz1S5O/PuChjjSEvGQKb0Dok2F8B3ckL7RI9vaaVqQ/UrzNWGsnsLdP/6wNWyMQ87i9p3Lk1u1wQBylpNVHHjkMqK2GMnqWMN3Z4XFwB7kZeT3Pq/r3zZODTbT/+jBLimugidmDRE8Ze+wSPc4wd6GJiMS+z8WDS0rWro81rlf1Ipiak8AzVafuW3XTfJXiHIheHiyafhetXw+6YC6FEqNrgGI70pltc/Bhq9CvvFMmePzhlJtriGwDzFYjP780CgecaDmCW2VAvGqYhDMr5wQtSP0Mo=
  template:
    metadata:
      creationTimestamp: null
      name: ledger-api-secrets
      namespace: ledger
